<a href="https://colab.research.google.com/github/Anusha-Chittiraju123/NASSCOM/blob/main/WEEK%202/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as numpy
# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)

Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [7]:
import numpy as np
# arange(): Create range of numbers like Python's range()
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)

Array using arange: [0 2 4 6 8]


In [8]:
import numpy as np
# reshape(): Change shape without changing data
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())


Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [9]:

# -----------------------------------------------------------
# 🔹 2. AGGREGATE FUNCTIONS
# -----------------------------------------------------------

data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)



Original Data:
 [[5 8 9]
 [2 4 6]]
